# Generated by Django 4.2.3 on 2023-07-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_useraddressinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressinformation',
            name='zipcode',
            field=models.CharField(default='', max_length=6),
        ),
    ]
