# Generated by Django 4.2.3 on 2023-07-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_useraddressinformation_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkSheetInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('math_marks', models.IntegerField()),
                ('english_marks', models.IntegerField()),
                ('teacher_marks', models.CharField(choices=[('Good', 'Good'), ('Average', 'Average'), ('Below Average', 'Below Average')], max_length=20)),
            ],
        ),
    ]
