# Generated by Django 4.2.3 on 2023-07-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_marksheetinformation_is_sports_team_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleMarkSheetInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('math_marks', models.IntegerField()),
                ('english_marks', models.IntegerField()),
                ('is_sports_team_member', models.BooleanField(default=False)),
            ],
        ),
    ]
