# Generated by Django 4.2.3 on 2023-07-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_samplemarksheetinformation_teacher_marks_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(default='', max_length=100)),
                ('article_description', models.CharField(default='', max_length=500)),
                ('is_article_publish', models.BooleanField(default=False)),
            ],
        ),
    ]
